### ISSUE TITLE
無法輸入ㄡ及minimal頁問題

### ISSUE THREAD

**Issue by ids93216** [timdream/jszhuyin#15]
無法輸入注音ㄡ，按了沒反應

github抓下來的minimal.html會顯示找不到data/database.data

**Comment by timdream** [comment]
Works for me on Firefox & Chrome。試著把 AppCache 清掉拿最新版看看？

`master` branch 不會有資料檔，使用前請先自己輸入 `grunt data` 建檔案。

**Comment by timdream** [comment]
還有問題請再留言啊

**Comment by ids93216** [comment]
依然不行，版本是44.0.2403.125m
Windows 7和Windows 10

![image](https://cloud.githubusercontent.com/assets/4828920/9034099/b5487e36-39ff-11e5-8a87-3976e236c7f4.png)

附上影片好了
https://youtu.be/xHKmZunNR1Q

**Comment by timdream** [comment]
讓我來開個 Windows VM 出來看看 ... Orz

**Comment by timdream** [comment]
可以幫我測一下那個鍵在

https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html

顯示的資料嗎？請把 "Old DOM3" 的 column 也打開。

**Comment by timdream** [comment]
喔不用了，我的 VM 終於起來了 ...

**Comment by timdream** [comment]
@ids93216 有看到的話還是幫我測一下好嗎？我懷疑 VM 裡面收到的 key data 跟實機不一樣。

**Comment by timdream** [comment]
Quote, Period, Backquote 都是爛掉的，不只有 Peroid。

**Comment by ids93216** [comment]
![image](https://cloud.githubusercontent.com/assets/4828920/9053169/c78729ae-3aa3-11e5-9eb1-a2f43d5da47d.png)

**Comment by timdream** [comment]
@ids93216 還有 「`」（ `1` 左邊的按鈕）跟反斜線 「\」也可以幫我測一下嗎？

**Comment by timdream** [comment]
應該在最新的 9eb5a703d7a10c161b59964cf6e4ed542f24cb40 修好了，如果你確定沒問題我就把這個 issue 關了。

**Comment by ids93216** [comment]
目前測試都正常，但是數字鍵區也有反應，這樣算正常嗎？

另外借題問，有辦法用按鈕來觸發輸入嗎？

**Comment by timdream** [comment]
> 目前測試都正常

OK! Close ...

> 但是數字鍵區也有反應，這樣算正常嗎？

現在的程式沒有判斷，但是可以做，有必要做嗎？有的話開新 Issue ... 不保證何時就是。

> 另外借題問，有辦法用按鈕來觸發輸入嗎？

可以，但是不想在這個專案的 repo 實作太複雜的像是虛擬鍵盤之類的介面 ... 也可以開個新 issue 說不定哪天我會回心轉意 :dancer:

**Comment by timdream** [comment]
謝謝幫忙啊！
