### ISSUE TITLE
請問有辦法做到其他字母搭配注音還是可以算出結果嗎?

### ISSUE THREAD

**Issue by LmanTW** [timdream/jszhuyin#54]
因為我現在正在製作一個簡單的2D遊戲引擎，我現在正在製作文字輸入部分，想說使用這個包來做到注音拼音

**Comment by LmanTW** [comment]
如
`ABCㄋㄧˇㄏㄠˇ` -> ABC你好
`ㄋㄧˇ好` -> 你好

**Comment by timdream** [comment]
聽起來做一些字串處理再把注音傳進去就能做到了。
這個功能沒有內建喔。
